CREATE DATABASE IF NOT EXISTS test;

USE test;

CREATE TABLE IF NOT EXISTS USERS (
    id CHAR(36) PRIMARY KEY,
    hashed_password VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    username VARCHAR(35),
    verified BOOLEAN DEFAULT FALSE
);
